name: Build ZMK

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:2.5

    strategy:
      matrix:
        shield: [kyria_rev2_left, kyria_rev2_right]

    steps:
      - uses: actions/checkout@v4

      - run: west init -l config
      - run: west update
      - run: west zephyr-export

      - run: west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=${{ matrix.shield }} -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - run: cp build/zephyr/zmk.uf2 ${{ matrix.shield }}_nice_nano_v2.uf2

      - uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.shield }}
          path: ${{ matrix.shield }}_nice_nano_v2.uf2
